name: UserStory_Validation
on:
  workflow_dispatch:
    inputs:
      Sample:
        type: choice
        options:
          - sample1
          - sample2
          - sample3
 
env:
  var1: valueofvar
jobs:
  Job1:
    runs-on: ubuntu-latest
    if: ${{ always() && inputs.Sample == 'sample1' }}
    steps:
      - run: |
          echo $var1 is var1
  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    if: ${{ always() && inputs.Sample == 'sample1' }}
    steps:
      - run: |
          echo $var1 is var1
  Job22:
    runs-on: ubuntu-latest
    needs: Job1
    if: ${{ always() && inputs.Sample == 'sample1' }}
    steps:
      - run: |
          echo $var1 is var1
  Job3:
    runs-on: ubuntu-latest
    needs: [Job1,Job2,Job22]
    # if: ${{ always() && inputs.Sample == 'sample1' }}
    if: ${{ inputs.Sample == 'sample1' }}
    steps:
      - run: |
          echo $var1 is var1        
 
         
