name: Email action

on:
  workflow_dispatch:  
jobs:
  Email-action:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-1
      
      - uses: actions/checkout@v3
      
      - run: |
          pwd
          ls -lrta
          
      - name: Step1
        run: |
          aws ses send-email --from athulyams2000@gmail.com --destination ToAddresses=athulyams2000@gmail.com --message file://message.json
          
          
          
