name: checkout_test
on:
  workflow_dispatch:

jobs:
  Test1:
    runs-on: ubuntu-latest 
      
    steps:
      - uses: actions/checkout@v3
      - run : |
          echo log of Test1 job
          jobs_url="https://api.github.com/repos/2115-27/hello-world-npm/actions/runs/${{ github.run_id }}/jobs"
          curl -s -H "Authorization: token ${{ secrets.LOGS_SECRET }}" $jobs_url
          job_id=$(curl -s -H "Authorization: token ${{ secrets.LOGS_SECRET }}" $jobs_url | jq -r '.jobs[] | select(.name == "${{ github.job }}" and .status == "in_progress") | .id')
          echo $job_id is job_id of Test1 job 
  Test:
    runs-on: ubuntu-latest 
    needs: Test1  
    outputs:
        job_id: ${{ steps.Branchname.outputs.job_id }}
    steps:
      - uses: actions/checkout@v3
      - name: Print the analysis branch
        run: |
          echo ${{ github.head_ref }}
          echo log line 
      - id: Branchname
        run: |
         
           jobs_url="https://api.github.com/repos/2115-27/hello-world-npm/actions/runs/${{ github.run_id }}/jobs"
           curl -s -H "Authorization: token ${{ secrets.LOGS_SECRET }}" $jobs_url
           job_id=$(curl -s -H "Authorization: token ${{ secrets.LOGS_SECRET }}" $jobs_url | jq -r '.jobs[] | select(.name == "${{ github.job }}" and .status == "in_progress") | .id')
           echo $job_id is job_id
           
           echo "job_id=$job_id" >> $GITHUB_OUTPUT
           
  Log:
    runs-on: ubuntu-latest 
    needs: Test  
    outputs:
        job_id: ${{ steps.Branchname.outputs.job_id }}
    steps:
      - uses: actions/checkout@v3
      - run: |    
           echo ${{ needs.Test.outputs.job_id }} is job id of test job
           
           jobs_url="https://api.github.com/repos/2115-27/hello-world-npm/actions/runs/${{ github.run_id }}/jobs"
           
           job_id=$(curl -s -H "Authorization: token ${{ secrets.LOGS_SECRET }}" $jobs_url | jq -r '.jobs[] | select(.name == "${{ github.job }}" and .status == "in_progress") | .id')
           echo $job_id is job_id of Log job
           
           echo "----------------gh command-----------"
           gh run view --job 11006386665 --log   
        env:
          GH_TOKEN: ${{ secrets.LOGS_SECRET }}  
