name: checkout_test
on:
  workflow_dispatch:

jobs:
  Test1:
    runs-on: ubuntu-latest 
      
    steps:
      - uses: actions/checkout@v3
      - run : echo log of Test1 job
  Test:
    runs-on: ubuntu-latest 
    needs: Test1  
    steps:
      - uses: actions/checkout@v3
      - name: Print the analysis branch
        run: |
          echo ${{ github.head_ref }}
          echo log line 
      - run: |
           curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.LOGS_SECRET }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/2115-27/hello-world-npm/actions/jobs/Test1/logs
           echo "----------------gh command-----------"
           gh run view ${{ github.run_id }} --log   
        env:
          GH_TOKEN: ${{ github.token }}   
