name: checkout_test
on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest 
      
    steps:
      - name: Print the analysis branch
        run: |
          echo ${{ github.head_ref }}
          echo log line 
        

      - run: |
           gh run view ${{ github.job }} --log   
        env:
          GH_TOKEN: ${{ github.token }}   
