name: checkout_test
on:
  workflow_dispatch:

jobs:
  Test1:
    runs-on: ubuntu-latest 
      
    steps:
      - uses: actions/checkout@v3
      - run : echo log of Test1 job
  Test:
    runs-on: ubuntu-latest 
    needs: Test1  
    outputs:
        job_id: ${{ steps.Branchname.outputs.Dev_branch }}
    steps:
      - uses: actions/checkout@v3
      - name: Print the analysis branch
        run: |
          echo ${{ github.head_ref }}
          echo log line 
      - id: Branchname
        run: |
         
           jobs_url="https://api.github.com/repos/2115-27/hello-world-npm/actions/runs/${{ github.run_id }}/jobs"
           curl -s -H "Authorization: token ${{ secrets.LOGS_SECRET }}" $jobs_url
           job_id=$(curl -s -H "Authorization: token ${{ secrets.LOGS_SECRET }}" $jobs_url | jq -r '.jobs[] | select(.name == "${{ github.job }}" and .status == "in_progress") | .id')
           echo $job_id is job_id
           
           echo "job_id=$job_id" >> $GITHUB_OUTPUT
           
      - run: |    
      
           echo "----------------gh command-----------"
           gh run view --job ${{ steps.Branchname.outputs.job_id }} --log   
        env:
          GH_TOKEN: ${{ secrets.LOGS_SECRET }}   
