name: Child

on:
  workflow_call:

jobs: 
  Memory: 
    runs-on: ubuntu-latest
    steps:

  
     - run: |
        echo failing child job
        echo ${{ github.workflow }} is workflow name
        echo yaml in another branch is called
        
        

     
