name: Child

on:
  workflow_dispatch:

jobs: 
  Memory: 
    runs-on: ubuntu-latest
    steps:

  
     - run: |
        
        current_date=$(date +'%m/%d/%Y')
        echo "Current date: $current_date"
        
        

     
