name: Child2

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string

jobs: 
  Child2: 
    runs-on: ubuntu-latest
    steps:

  
     - run: |
        echo ${{ github.workflow }} is parent
        echo ${{ inputs.status }} is Child status
