name: Memory

on:
  workflow_dispatch:

jobs: 
  Memory: 
    runs-on: ubuntu-latest
    steps:

  
     - run: |
     
         TOKEN=$(echo 'latin string' | iconv -t utf-8 | base64)
         echo $TOKEN
          
