name: Version_Updator
on:
  workflow_call:
jobs:
   VersionUpdation: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          ENV=$(echo ${{ github.event.inputs.Environment }} | tr '[:lower:]' '[:upper:]')
          echo $ENV is the environment
          echo $Component_Name is the component name

