name: Version_Updator
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      CompName:
        required: true
        type: string    
 
jobs:
   VersionUpdation: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          ENV=$(echo ${{ github.event.inputs.Environment }} | tr '[:lower:]' '[:upper:]')
          echo $ENV is the environment
          ComponentName=${{ inputs.CompName }}
          echo $ComponentName is the component name

