name: Delete-tag-and-release
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        ref: '1.0-SNAPSHOT'
     - name: Deleting Snapshot version
       run: | 
            gh release list >> release.txt
            ls -lrta
            cat release.txt
            while read line; do echo $line; done < release.txt
            grep -i "^1.0-SNAPSHOT" release.txt | { grep -v grep || true; }
           
       env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
