name: Delete-tag-and-release
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
     - name: Deleting Snapshot version
       run: |
        
            gh release delete-asset 1.0-SNAPSHOT AppName1.0-SNAPSHOT.zip
            gh release delete 1.0-SNAPSHOT
        
       env:
           GHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
