name: Delete-tag-and-release
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - run: curl -u 2115-27:Athulya@2115 --request DELETE "https://api.github.com/repos/2115-27/hello-world-npm/releases/169"
