name: Delete-tag-and-release
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
     - name: Deleting Snapshot version
       run: |        
            gh release delete 1.0-SNAPSHOT -y
       env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
