name: Delete-tag-and-release
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        ref: '1.0-SNAPSHOT'
     - name: Deleting Snapshot version
       run: | 
            gh release list >> release.txt
            ls -lrta
            echo ---------------file content---------
            cat release.txt
            echo ----------------- each line content-----------------
            while read line; do echo $line; done < release.txt
            echo -------------checks for snapshot version and deleting if it exists----------------------------
            snapversion=$(grep -i "^AppName-1.0-SNAPSHOT" release.txt | { grep -v grep || true; })
            echo $snapversion
            if [ -z "$snapversion" ];then
              echo "Skipping deletion since 1.0-SNAPSHOT version doesn't exist already"              
            else
              gh release delete 1.0-SNAPSHOT
            fi  
           
       env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
