name: Download Package

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - run: |
          curl -vLJO -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' 'https://api.github.com/repos/2115-27/hello-world-npm/releases/testrelease'
          ls -lrta
    - name: untar      
      run:  |
          
          tar zxvf testrelease
          ls -lrta
#     - name: list contents of .tgz  
#       run:    tar -ztvf hello-world-npm-pkg-22.2.96-npm.tgz
#     - name: list contents of hello-world-npm-pkg
#       run:    cat hello-world-npm-pkg
#     - name: pwd is.....
#       run: pwd
          
