name: A-Get Time diff

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - run: |
       sudo timedatectl set-timezone CET
       timedatectl
       timedatectl >> time.txt
       echo -----------------------------
       cat time.txt
