name: A-Get Time diff

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 5,13 * * *'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:

    - run: |
        touch file.pem
        ls
        Icacls file.pem
        
    # - uses: actions/checkout@v3
    # - run: |
    #       git config user.name "${{ runner.name }}"
    #       git config user.email "$(hostname -f)"  
          
    #       echo test > ${{ github.workspace }}/release-note.html
    #       git add ${{ github.workspace }}/release-note.html
    #       git status
    #       git commit -m "Adding release-note.html file changes"
          
    #       git push origin HEAD:master --force
