name: Download Package

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - run: |
          curl -vLJO -H 'Authorization:${{ secrets.GITHUB_TOKEN }}' 'https://api.github.com/repos/2115-27/hello-world-npm/releases/assets/22.02.000'
          ls -lrta
