name: Install Package

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - run: |
        npm install @2115-27/hello-world-npm-pkg@22.2.96
        ls -lrta
#     - name: unzip      
#       run:  |
         
#           ls -lrta
#           unzip *.zip
#           ls -lrta
#     - name: list contents of .tgz  
#       run:    tar -ztvf hello-world-npm-pkg-22.2.96-npm.tgz
#     - name: list contents of hello-world-npm-pkg
#       run:    cat hello-world-npm-pkg
#     - name: pwd is.....
#       run: pwd
          
