name: Download Package

on:
  workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - run: |
         curl -H "Accept: application/vnd.github+json" -H "Authorization: token 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" https://api.github.com/orgs/2115-27/packages/npm/hello-world-npm-pkg@22.2.96
#     - name: unzip      
#       run:  |
         
#           ls -lrta
#           unzip *.zip
#           ls -lrta
#     - name: list contents of .tgz  
#       run:    tar -ztvf hello-world-npm-pkg-22.2.96-npm.tgz
#     - name: list contents of hello-world-npm-pkg
#       run:    cat hello-world-npm-pkg
#     - name: pwd is.....
#       run: pwd
          
