name: Download Package

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - run: |
          wget https://github.com/2115-27/hello-world-npm/archive/refs/tags/22.02.096.zip
          ls -lrta
    - name: unzip      
      run:  |
         
          ls -lrta
          unzip *.zip
          ls -lrta
#     - name: list contents of .tgz  
#       run:    tar -ztvf hello-world-npm-pkg-22.2.96-npm.tgz
#     - name: list contents of hello-world-npm-pkg
#       run:    cat hello-world-npm-pkg
#     - name: pwd is.....
#       run: pwd
          
