name: DYNA_TEST
on:
  workflow_dispatch:
 
jobs:

    Get-Commit-History: 
#           needs: [RefreshDynaJS]
          runs-on: ubuntu-latest
          steps: 
            - uses: actions/checkout@v3
#             - run: |
#                 git log 
                
            - name: curl command to list workflow runs
              run: |
                 curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs"
              env:
                GH_TOKEN: ${{ github.token }}   
