name: DYNA_TEST
on:
    - pull_request
          
jobs:
        PR-commits:

          runs-on: ubuntu-latest
          steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            with:
                ref: ${{ github.event.pull_request.head.ref }}

          - name: View Pull Request
            run: |
                echo ------------------commits---------------------
                gh pr view --json commits
                echo ----------------------file--------------------
                gh pr view -c --json commits --jq '.commits' > pr-info.json

                cat pr-info.json 
                
                echo ------------------------commits.md---------------------------------
                jq -r '.[] | "| \(.authors[0].name) | \(.messageHeadline) | \(.oid) |"' pr-info.json > commits.md
                
                cat commits.md
          
            env:
               GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET }} 
               
          - run: |
              mkdir Current-branch
              cd Current-branch/
          
          - name: Checkout branch
            uses: actions/checkout@v3
            with: 
              ref: 'base-branch'
          
          - run: |
              cp commits.md .
              git add commits.md
              git commit -m "Changes in recent PR"
              git push origin base-branch
               
            env:
               GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET }}     
