name: DYNA_TEST
on:
    - pull_request
  
          
jobs:

        PR-commits:

          runs-on: ubuntu-latest
          steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            with:
                ref: ${{ github.event.pull_request.head.ref }}

          - name: View Pull Request
            run: |

                gh pr view -c --json number,title,author,body --jq '.number,.title,.author,.body' > pr-info.json

                cat pr-info.json 
                echo -----------------view command---------------------
                gh pr view
                
            env:
               GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET }}     
