name: DYNA_TEST
on:
  workflow_dispatch:
  
      inputs: 
       version:
        description: 'Version'
        required: true
        type: string       
       environment:
        required: true
        type: choice
        description: environment
        options: 
          - pg
          - agt
          - wgpg
          - aspg
          - dev
          - test
   
jobs:

    testJob2: 
#           needs: [RefreshDynaJS]
          runs-on: ubuntu-latest
          steps: 
            -  run: echo ${{ github.workflow }} is workflow name 
