name: DYNA_TEST
on:
  workflow_dispatch:
 
jobs:
    Date:
      runs-on: ubuntu-latest
      steps:
        - run: date -u -d "2023-05-24T22:00:00Z" +"%Y-%m-%d %H:%M:%S" -d "2 hours"


#     Get-Commit-History: 
# #           needs: [RefreshDynaJS]
#           runs-on: ubuntu-latest
#           steps: 
#             - uses: actions/checkout@v3
#             - name: Generate Commit History
#               run: |
#                 echo ############### git fetch command ###########################
#                 git fetch --unshallow || true
#                 echo ################### git log #################################
#                 git log --format="- %s (%an)" $(git describe --tags --abbrev=0)..HEAD > commit_history.txt
#                 echo #################### commit_history.txt ########################
#                 cat commit_history.txt
                
                
                
#             - run: |
#                 git log 
                
#             - name: curl command to list workflow runs
#               run: |
                 
#                  PreviousRunID=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs" | jq -r '.workflow_runs[2].id')
#                  CurrentRunID=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs" | jq -r '.workflow_runs[1].id')
#                  echo $PreviousRunID is PreviousRunID
#                  echo $CurrentRunID is CurrentRunID
#                  echo ${{ github.run_id }} is github.run_id
                 
#                  curl -s "https://api.github.com/repos/${{ github.repository }}/actions/runs/37222667/commits"
                 
#                  echo ##################################################
#                  git log
#                  echo -------------------------------------
#                  git log fa8f8d6..161976c
                 
#               env:
#                 GH_TOKEN: ${{ github.token }}   
