name: DYNA_TEST
on:
    - pull_request
          
jobs:
        PR-commits:

          runs-on: ubuntu-latest
          steps:
          - name: Checkout Repository
            uses: actions/checkout@v2
            with:
                ref: ${{ github.event.pull_request.head.ref }}

          - name: View Pull Request
            run: |
                echo ------------------commits---------------------
                gh pr view --json commits
                echo ----------------------file--------------------
                gh pr view -c --json commits --jq '.commits' > pr-info.json

                cat pr-info.json 
                
                echo -----------deleting already existing commits.md file--------------------
                if [ -f "commits.md" ]; then
                    rm "commits.md"
                fi
                
                echo ------------------------commits.md---------------------------------
                PRNumber=$(gh pr view -c --json number --jq '.number')
                echo $PRNumber is PRNumber
                url="https://github.com/${{ github.repository }}/pull/$PRNumber/commits/"
                echo $url is url
                jq -r --arg url "$url" '.[] | "- \(.authors[0].name) - \(.messageHeadline) - [\("details")](\($url + "/" + .oid)) "' pr-info.json | while IFS= read -r line; do echo "$line" >> commits.md; done
               
                cat commits.md
                
               
          
            env:
               GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET }} 
               
          - run: |
              pwd
              ls -lrta
              mkdir Current-branch
              echo ---------------current branch is here-------------
              pwd
              ls -lrta

          
          - name: Checkout branch
            uses: actions/checkout@v3
            with: 
              ref: 'base-branch'
              path: 'Current-branch'
          
          - run: |
              pwd 
              ls -lrta
              cp commits.md Current-branch
              cd Current-branch/
              ls -lrta
              
          - name: Set identity and push
            run: |
              git config user.name "${{ runner.name }}"
              git config user.email "$(hostname -f)"  
              
              git add commits.md
              git commit -m "Changes in recent PR"
              git push origin branch-for-pr
               
            env:
               GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET }}     
