name: DYNA_TEST
on:
  workflow_dispatch:
 
jobs:

    Get-Commit-History: 
#           needs: [RefreshDynaJS]
          runs-on: ubuntu-latest
          steps: 
            - uses: actions/checkout@v3
            - run: |
                git log --decorate --oneline --graph
