name: DYNA_TEST
on:
  workflow_dispatch:
  
      inputs: 
       version:
        description: 'Version'
        required: true
        type: string       
       environment:
        required: true
        type: choice
        description: environment
        options: 
          - pg
          - agt
          - wgpg
          - aspg
          - dev
          - test
   
jobs:
    jdk-version:      
        runs-on: ubuntu-latest
        steps: 
          -  run: java -version 

    RefreshDynaJS:
          name: Refresh Dynatrace js
          needs: jdk-version
          uses: ./.github/workflows/test-refresh-dynatrace-js.yml
          with:
           environment: ${{ github.event.inputs.environment }}


    testJob2: 
          needs: [RefreshDynaJS]
          runs-on: ubuntu-latest
          steps: 
            -  run: echo testing
