name: NPM_TEST
on:
  workflow_dispatch:
  
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run:  |
             npm install -g @angular/cli@latest   
             echo ---------ng version----------------
             ng version
             echo --------------------npm version-----------
             npm --version
             pwd
             ls -ahl
      
