name: output test
on:
  workflow_dispatch:
       

jobs:

   Job1:    
     runs-on: macos-latest
     steps:
       - run: |
 
          xmllint --version
       - run: |
          
          PlistBuddy --version
