name: output test
on:
  workflow_dispatch:
       

jobs:

   Job1:    
     runs-on: macos-latest
     steps:
       - run: jarsigner -help
       - run: |
 
          xmllint --version
       - run: |
          ls -lrta /usr/libexec/PlistBuddy
          /usr/libexec/PlistBuddy Help
