name: output test
on:
  workflow_dispatch:
       

jobs:

   Job1:    
     runs-on: ubuntu-latest
     steps:
       - run: |
          sudo apt-get install -y libxml2-utils
          xmllint --version
          plistbuddy --version
