name: output test
on: 
  workflow_dispatch:    

jobs:  
  
  Build-Validation:
      runs-on: ubuntu-latest

      steps:
        - name: Set Branch Parameters
          id: envid
          run: |
               echo $REPO_NAME is repo name
                   
  
 
