name: Parentworkflow
on:
  workflow_dispatch:
jobs:
   
#      Set_ReleaseVersion_Variable: 
#       runs-on: ubuntu-latest
#       outputs:
#         Version: ${{ steps.versionid.outputs.Version }}

#       steps:
#         - id: versionid
#           run: | 
#                echo setting release version!!
#                newversion="23.01.0.147"
#                echo $newversion is the version
#                echo "Version=$newversion" >> $GITHUB_OUTPUT
     TestJob: 
      runs-on: ubuntu-latest
#       needs: [Set_ReleaseVersion_Variable]
      steps:   
        - run: echo testing parent 
     
     Job2:
      needs: TestJob
#       if: ${{ always() && needs.TestJob.result == 'skip' }}
      uses: ./.github/workflows/child.yml
      
     Job3:
       needs: Job2
       if: ${{ always() && ((needs.Job2.result == 'failure') || (needs.Job2.result == 'success')) }}
       uses: ./.github/workflows/child2.yml
       
         
         
