name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Brand:
          description: 'Brand Type'
          type: choice
          required: true
          options:
            - child2
            - BRAND 1
            - Brand2
            - Brand3


jobs:
     
     TestJob: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            #response=$(curl -s -o /dev/null -w "%{http_code}" "https://api.github.com/repos/2115-27/hello-world-npm/contents/commits.md?ref=master")
            echo $response is the response
          
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             

     
     ChildJob:
       needs: TestJob
       uses: ./.github/workflows/${{ inputs.Brand }}.yml
       with:
         Brand: ${{ inputs.Brand }}
       secrets:
         REPO: ${{ secrets.REPO }}
         
         
         
