name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Deployment-Slot:
          description: 'Deployment Slot'
          type: choice
          required: true
          options:
            - 12:00 PM
            - 7:15 PM

run-name: SecondBrandName
jobs:
   
#      Set_ReleaseVersion_Variable: 
#       runs-on: ubuntu-latest
#       outputs:
#         Version: ${{ steps.versionid.outputs.Version }}

#       steps:
#         - id: versionid
#           run: | 
#                echo setting release version!!
#                newversion="23.01.0.147"
#                echo $newversion is the version
#                echo "Version=$newversion" >> $GITHUB_OUTPUT
     TestJob: 
      runs-on: ubuntu-latest
#       needs: [Set_ReleaseVersion_Variable]
      steps:   
        - name: Checkout code
          uses: actions/checkout@v3
        - run: |
            echo -----------------------run-name-----------------------------
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/workflows/parent.yml/runs?status=in_progress" 
            RUN_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/workflows/parent.yml/runs?status=in_progress" |  jq -r '.workflow_runs[1].id')
            echo RUN_ID: $RUN_ID
            echo ----------------------input--------------------------
            RUN_NAME=$(curl -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/runs/$RUN_ID" |  jq -r '.name')
            echo RUN_NAME: $RUN_NAME
          env:
            GH_TOKEN: ${{ SECRETS.REPO }}
        - run: sleep 120    
     
#      Job2:
#       needs: TestJob
# #       if: ${{ always() && needs.TestJob.result == 'skip' }}
#       uses: 2115-27/hello-world-npm/.github/workflows/child.yml@anotherbranch
      
#      Job3:
#        needs: TestJob
#        #if: ${{ always() && ((needs.Job2.result == 'failure') || (needs.Job2.result == 'success')) }}
#        uses: ./.github/workflows/child2.yml
#        with:
#          status: ${{ needs.Job2.result }}
         
         
