name: Parentworkflow
on:
  workflow_dispatch:
jobs:
   
#      Set_ReleaseVersion_Variable: 
#       runs-on: ubuntu-latest
#       outputs:
#         Version: ${{ steps.versionid.outputs.Version }}

#       steps:
#         - id: versionid
#           run: | 
#                echo setting release version!!
#                newversion="23.01.0.147"
#                echo $newversion is the version
#                echo "Version=$newversion" >> $GITHUB_OUTPUT
     TestJob: 
      runs-on: ubuntu-latest
#       needs: [Set_ReleaseVersion_Variable]
      steps:   
        - run: echo testing parent 
     
     Send-email:
 
       needs: [TestJob]         
       uses: ./.github/workflows/aws-email.yml
       secrets:
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
       
         
         
