name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Deployment-Slot:
          description: 'Deployment Slot'
          type: choice
          required: true
          options:
            - 12:00 PM
            - 7:15 PM
    
jobs:
   
#      Set_ReleaseVersion_Variable: 
#       runs-on: ubuntu-latest
#       outputs:
#         Version: ${{ steps.versionid.outputs.Version }}

#       steps:
#         - id: versionid
#           run: | 
#                echo setting release version!!
#                newversion="23.01.0.147"
#                echo $newversion is the version
#                echo "Version=$newversion" >> $GITHUB_OUTPUT
     TestJob: 
      runs-on: ubuntu-latest
#       needs: [Set_ReleaseVersion_Variable]
      steps:   
        - run: |
           
           echo test
           DATE=$(date +%Y/%m/%d_%H:%M:%S)
           echo $DATE 
           date -d "12:00 PM" +"%H:%M:%S"
     
#      Job2:
#       needs: TestJob
# #       if: ${{ always() && needs.TestJob.result == 'skip' }}
#       uses: 2115-27/hello-world-npm/.github/workflows/child.yml@anotherbranch
      
#      Job3:
#        needs: Job2
#        if: ${{ always() && ((needs.Job2.result == 'failure') || (needs.Job2.result == 'success')) }}
#        uses: ./.github/workflows/child2.yml
#        with:
#          status: ${{ needs.Job2.result }}
         
         
