name: Parentworkflow
on:
  workflow_call:
    inputs:
      Brand: 
        type: string
  workflow_dispatch:
    
jobs:
     
     TestJob: 
      runs-on: ubuntu-latest
      steps:
        - run: |
           SlotDateTime1="\$(date +"%y-%m-%d")"
           SlotDateTime2="$(date +"%y-%m-%d")"
           echo $SlotDateTime1 is SlotDateTime1
           echo $SlotDateTime2 is SlotDateTime2
 
       
