name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Brand:
          description: 'Brand Type'
          type: choice
          required: true
          options:
            - BRAND 1
            - Brand2
            - Brand3
  pull_request:
     types: [closed]
 
 
 
#     inputs: 
#        Brand:
#           description: 'Brand Type'
#           type: choice
#           required: true
#           options:
#             - BRAND 1
#             - Brand2
#             - Brand3


jobs:
     
     TestJob: 
      runs-on: ubuntu-latest
      steps:
#         - run: mkdir master/
        
        - name: Checkout
          uses: actions/checkout@v3
#           with:
#             path: master
            
        - run: |
            PRNumber=$(gh pr view ${{ github.event.pull_request.head.ref }} --json number --jq '.number')
            echo $PRNumber is PRNumber
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
#         - run: |
#             ls -lrta    
#             cd master/
#             ls -lrta
#             echo ----------------workspace-----------------------
#             echo ${{ github.workspace }}
#             pwd
#             if [[ -f "${{ github.workspace }}/master/testing.md" ]]; then
#               echo file exists
#             else
#               echo file does not exists
#             fi  

#         - run: |
#             response=$(curl -s -o "output_file" -w "%{http_code}" "https://api.github.com/repos/2115-27/hello-world-npm/contents/testing.md?ref=branch-for-testing")
#             echo $response is the response
#             download_url=$(jq -r '.download_url' "output_file")
#             curl -s -o "file_content" $download_url
#             cat file_content 
          
#           env:
#              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             
#         - run: |
#             echo ${{ github.run_number }}
#             $Brand="${{ inputs.Brand }}"
#             echo "Brand=$Brand"
#             $folder="$Brand"
#             echo "folder=$folder"
#         - name: Zip workspace
#           run: |
           
#            7z a "workspace-${{ github.workflow }}-${{ github.run_number }}.zip" "./"
#            ls
           
#         - name: Upload workspace as artifact
#           if: always()
#           uses: actions/upload-artifact@v3
#           with:
#                name: Workspace of ${{ github.workflow }} RunNumber-${{ github.run_number }}
#                path: workspace-${{ github.workflow }}-${{ github.run_number }}.zip
#                retention-days: 7
               
#         - name: Checkout code
#           uses: actions/checkout@v3
        
#         - run: |
#              echo Brand1 status= ${{ vars.BRAND1 }}
#              sleep 30
             
#         - run: |
#             if [ ${{ inputs.Brand == 'BRAND1' }} ]; then
#               echo checking state of brand1
#               while [ ${{ vars.BRAND1 == 'in_progress' }} ]; do
#                   if [ ${{ vars.BRAND1 == 'completed' }} ]; then
#                      continue
#                   else
#                     echo execution for brand1 is still in progress
#                   fi
#                   echo sleeping before checking again
#                   echo Brand1 status= ${{ vars.BRAND1 }}
#               done  
#             fi  
#         - run: echo Brand1 status= ${{ vars.BRAND1 }}
        
#         - run: |
#             echo test
#             echo ${{ vars.BRAND1 }} is status of BRAND1
#             echo in_progress > myfile.txt 
#             cat myfile.txt
#             gh variable set BRAND1 < myfile.txt
#             echo ${{ vars.BRAND1 }} is status of BRAND1 after updation
#           env:
#             GH_TOKEN: ${{ secrets.REPO }}
     
     ChildJob:
       needs: TestJob
       uses: ./.github/workflows/child2.yml
       with:
         Brand: ${{ inputs.Brand }}
       secrets:
         REPO: ${{ secrets.REPO }}
         
         
         
