name: A-Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       OtherInput:
          description: 'Brand Type'
          type: choice
          required: true
          options:
            - BRAND 1
            - Brand2
            - Brand3


jobs:
     
     ChildJob:
       uses: ./.github/workflows/parent.yml
       with:
         Brand: ${{ inputs.Brand }}
         
         
         
