name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Brand:
          description: 'Brand'
          type: choice
          required: true
          options:
            - Brand1
            - Brand2
            - Brand3

run-name: ${{ inputs.Brand }}
jobs:
   
     TestJob: 
      runs-on: ubuntu-latest
      steps:   
        - name: Checkout code
          uses: actions/checkout@v3
        
        - run: |
            echo test
            echo ${{ vars.BRAND1 }} is status of BRAND1
            
     
#      ChildJob:
#        needs: TestJob
#        uses: ./.github/workflows/child2.yml
#        with:
#          Brand: ${{ inputs.Brand }}
#        secrets:
#          REPO: ${{ secrets.REPO }}
         
         
         
