name: Parentworkflow
on:
  workflow_dispatch:
jobs:
   
     TestJob: 
      runs-on: windows-latest
#       needs: [Set_ReleaseVersion_Variable]
      steps:   
        - uses: actions/checkout@v3
        - run: |
            
            Get-ChildItem -Path ${{ github.workspace }}
            Get-ChildItem -Path ./

     
#      Job2:
#       needs: TestJob
#       uses: ./.github/workflows/child.yml
      
#      Send-email:
#        if: always()
#        needs: [TestJob,Job2]         
#        uses: ./.github/workflows/aws-email.yml
#        secrets:
#           AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID  }}
#           AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
       
         
         
