name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Brand:
          description: 'Brand'
          type: choice
          required: true
          options:
            - BRAND1
            - Brand2
            - Brand3

run-name: ${{ inputs.Brand }}
jobs:
     
     TestJob: 
      runs-on: ubuntu-latest
      steps:   
        - name: Checkout code
          uses: actions/checkout@v3
        
        - run: |
             echo Brand1 status= ${{ vars.BRAND1 }}
             sleep 30
             
#         - run: |
#             if [ ${{ inputs.Brand == 'BRAND1' }} ]; then
#               echo checking state of brand1
#               while [ ${{ vars.BRAND1 == 'in_progress' }} ]; do
#                   if [ ${{ vars.BRAND1 == 'completed' }} ]; then
#                      continue
#                   else
#                     echo execution for brand1 is still in progress
#                   fi
#                   echo sleeping before checking again
#                   echo Brand1 status= ${{ vars.BRAND1 }}
#               done  
#             fi  
        - run: echo Brand1 status= ${{ vars.BRAND1 }}
        
        - run: |
            echo test
            echo ${{ vars.BRAND1 }} is status of BRAND1
            echo in_progress > myfile.txt 
            cat myfile.txt
            gh variable set BRAND1 < myfile.txt
            echo ${{ vars.BRAND1 }} is status of BRAND1 after updation
          env:
            GH_TOKEN: ${{ secrets.REPO }}
     
#      ChildJob:
#        needs: TestJob
#        uses: ./.github/workflows/child2.yml
#        with:
#          Brand: ${{ inputs.Brand }}
#        secrets:
#          REPO: ${{ secrets.REPO }}
         
         
         
