name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Brand:
          description: 'Brand'
          type: choice
          required: true
          options:
            - Brand1
            - Brand2
            - Brand3

run-name: ${{ inputs.Brand }}
jobs:
   
     TestJob: 
      runs-on: ubuntu-latest
      steps:   
        - name: Checkout code
          uses: actions/checkout@v3
        
        - run: |
            echo -----------------------run-id-----------------------------
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/workflows/parent.yml/runs?status=in_progress" 
            RUN_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/workflows/parent.yml/runs?status=in_progress" |  jq -r '.workflow_runs[1].id')
            echo RUN_ID: $RUN_ID
            echo ----------------------run-name--------------------------
            RUN_NAME=$(curl -H "Authorization: Bearer ${{ secrets.REPO }}" "https://api.github.com/repos/2115-27/hello-world-npm/actions/runs/$RUN_ID" |  jq -r '.name')
            echo RUN_NAME: $RUN_NAME
          env:
            GH_TOKEN: ${{ SECRETS.REPO }}
        
        - run: sleep 120    
     
     ChildJob:
       needs: TestJob
       uses: ./.github/workflows/child2.yml
       with:
         Brand: ${{ inputs.Brand }}
       secrets:
         REPO: ${{ secrets.REPO }}
         
         
         
