name: Parentworkflow
on:
  workflow_dispatch:
    inputs: 
       Brand:
          description: 'Brand Type'
          type: choice
          required: true
          options:
            - child2
            - BRAND 1
            - Brand2
            - Brand3


jobs:
     
     TestJob: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: |
            ls -lrta
             

     
     ChildJob:
       needs: TestJob
       uses: ./.github/workflows/child.yml
      
         
         
         
