name: parsingtest
on:
  workflow_dispatch:

jobs:
  parsing:
    runs-on: ubuntu-latest 
      
    steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           ref: ${{ github.head_ref }}
      
      
