name: parsingtest
on:
  workflow_dispatch:

jobs:
  parsing:
    runs-on: ubuntu-latest 
      
    steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           ref: ${{ github.head_ref }}
       -  run: |
             ls -lrta
             firsturl="newvalueoffirsturl"
             secondurl="newvalue2"
             thirdurl="newvalue3"
             
             echo $firsturl
             echo $secondurl
             echo $thirdurl
             
             mv test-app-config.json temp.json
             jq -r '.firsturl= "adar"' temp.json > test-app-config.json
             rm temp.json
             echo -------file content after parsing-------
             cat test-app-config.json 
           
      
