name: parsingtest
on:
  workflow_dispatch:

jobs:
  parsing:
    runs-on: ubuntu-latest 
      
    steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           ref: ${{ github.head_ref }}
       -  run: |
             ls -lrta
             firsturl="newvalueoffirsturl"
             secondurl="newvalue2"
             thirdurl="newvalue3"
             
             echo $firsturl
             echo $secondurl
             echo $thirdurl
             
             address="abcde"
             age="22"
             echo $address
             echo $age
             tmp=$(mktemp) 
             jq --arg address "$address" --arg age "$age" '.address = "$address" | .age = "$age"' UIdeployment/appname/app-confg/test.json > "$tmp" && mv "$tmp" UIdeployment/appname/app-confg/test.json
             cat UIdeployment/appname/app-confg/test.json
           
      
