name: parsingtest
on:
  workflow_dispatch:

jobs:
  parsing:
    runs-on: ubuntu-latest 
      
    steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
           ref: ${{ github.head_ref }}
       -  run: |
             ls -lrta
             firsturl="newvalueoffirsturl"
             secondurl="newvalue2"
             thirdurl="newvalue3"
             
             echo $firsturl
             echo $secondurl
             echo $thirdurl
             
             tmp=$(mktemp) | jq '.address = "abcde"' test.json > "$tmp" && mv "$tmp" test.json
             cat test.json
           
      
