name: POWERSHELL
on:
  workflow_dispatch:
  
jobs: 
  output-test:
   runs-on: windows-latest  
   steps:
    - name: Set the value
      id: step_one
      run: |
        
        echo "FOO=BAR" >> $GITHUB_OUTPUT
    - name: Use it
      run: echo "${{ steps.step_one.outputs.FOO }}"
  
  Reponame:
    runs-on: windows-latest
    steps:
      - run: |
            $PackageName="new"
            $Release_Version="22.03.1"
            mkdir $PackageName-$Release_Version
            
             echo "----inside newdirectory------"
             cd $PackageName-$Release_Version
             New-Item file1
             dir
