name: Pull Request Labeler
on:
 pull_request:
    types: [opened,synchronize,reopened]
    branches:
      - master
      
    paths:
      - 'src/app/apps/**/*' 
      - '.github/**/*'

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  PRTest_branch_Protection:
    if: ${{ github.actor == 'noUser' }}
    needs: triage
    runs-on: ubuntu-latest
    steps:
    - run: echo testing  
