name: Pull Request Test
on:
 pull_request:
    types: [opened,synchronize,reopened]
    branches:
      - master
      
    paths:
      - 'etc/mail/**/*'
      - '.github/**/*'


jobs:
  PRTest_branch_Protection:
  
    runs-on: ubuntu-latest
    steps:
    - run: echo testing
