name: PR Check
on:
  pull_request:
    branches:
      - master
      
jobs:
  viewpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: view contents
        run: |
          gh pr checkout 26
          gh pr view -c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
