name: PR Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      
jobs:
  viewpr:
    runs-on: ubuntu-latest
    steps:
      - name: echo "$GITHUB_REF_NAME is the branchname"
      - uses: actions/checkout@v3 
      - name: view contents
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          gh pr view 33 >> comments.txt 
          task=$(grep "AB#" comments.txt)
          echo $task is task
          task1=$(echo $task | awk -F'[[:blank:]]' '{print $1}')
          echo $task1 is task1
          if [[ $task1 =~ ^AB#.*[0-9]$ ]];then
            echo valid number
            exit 0
          else
            echo invalid number
            exit 1
          fi  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
