name: PR Check
on:
  pull_request:
    branches:
      - master
      
jobs:
  viewpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: view contents
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          gh pr view $PR_NUMBER >> comments.txt 
          echo ----comments.txt--------
          cat comments.txt
          task=$(grep "AB#" comments.txt)
          echo $task 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
