name: PR Check
on:
  workflow_dispatch:
  pull_request:
    types: [opened,synchronize,reopened]
    branches:
      - PR-path_check
      
    paths:
      - 'src/**/*' 
      - 'etc/**/*'
      
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo test
         echo ${{ github.event.pull_request.changed_files }}
