name: PR Check
on:
  pull_request:
    branches:
      - master
      
jobs:
  viewpr:
    runs-on: ubuntu-latest
    steps:
      - name: view contents
        run: |
          gh pr view
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
