name: PR Check
on:
  workflow_dispatch:
  pull_request:
    types: [opened,synchronize,reopened]
    branches:
      - PR-path_check
      
    paths:
      - 'src/**/*' 
      - 'etc/**/*'
      
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo test
         echo ${{ github.event.pull_request.changed_files }}

      - name: Conditional step
        if: ${{ contains(github.event.pull_request.changed_files, 'src/') && contains(github.event.pull_request.changed_files, 'etc/') }}
        run: |
           echo both paths are changed
           
