name: SEND EMAIL

on:
  workflow_dispatch:

jobs: 
  Email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: ls -lrta
      
      - name: Install mailutils
        run: |
         sudo apt-get install -y mailutils
         
      - run: ls -lrta
      
#       - name: send email
#         run: |
#          echo "Test mail from GitHub with action details" >> email.txt
#          cat email.txt | mailx -s "Test mail from GitHub" shiyamsundar5796@gmail.com
        
        
         
#       - name: Send mail
#         uses: dawidd6/action-send-mail@v3
#         with:

#           server_address: smtp.office365.com
#           server_port: 587
#           # Optional whether this connection use TLS (default is true if server_port is 465)
#           username: ${{secrets.MAIL_USERNAME}}
#           password: ${{secrets.MAIL_PASSWORD}}        
#           subject: Test email
#           to: shiyamsundar.k@infosys.com
#           # Required sender full name (address can be skipped):
#           from: athulya.s01@infosys.com
#           body: Testing email sending action
#           priority: low
