name: DLT_STALE

on:
  workflow_dispatch:

jobs: 
  listStaleBranches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} 
          
      - name: List stale branches
        run:  |
            curl \
            -H "Accept: application/vnd.github+json" \ 
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/2115-27/hello-world-npm/branches
