name: STG_DEPLOY
on:
  workflow_call:
  schedule:
    - cron: '*/5 * * * *'
jobs:        
   Deploy:
    runs-on: ubuntu-latest
    environment: STG
    steps: 
      - run: |
          echo stage deployment steps
      - name: disable workflow
        run:  |
          gh workflow disable STGdeploy.yml -R 2115-27/hello-world-npm
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
