name: STG_DEPLLOY
on:
  workflow_call:
  schedule:
    - cron: '*/5 * * * *'
jobs:        
   Deploy:
    runs-on: ubuntu-latest
    environment: STG
    steps: 
      - run: |
          echo stage deployment steps
