name: test

on:
  workflow_dispatch:  

  
jobs:  

  version:
   runs-on: ubuntu-latest
   steps:
     - run: echo version
     
  testa:
    runs-on: ubuntu-latest
    needs: version
    continue-on-error: true
    steps:
      - run: |
          cd directory/
          touch file1.txt file2.txt  
          ls -lrta
          
          
  testb:
    runs-on: ubuntu-latest
    needs: version
    steps: 
      - run: echo test b!!
      
  testc:
    runs-on: ubuntu-latest
    needs: [testa,testb]
    steps: 
      - run: echo test c!!  
      
  testd:
    runs-on: ubuntu-latest
    needs: testc
    steps: 
      - run: echo test d!!    
