name: variabletest
on:
  workflow_dispatch:
      inputs: 
       version:
        description: 'Version'
        default: '1.0-SNAPSHOT'
        required: true
        type: string
       environment:
        type: choice
        description: environment
        options: 
        - pg
        - wgpg
        - aspg
        - agt
        - dev
        - test
        - stg
        - hotfix

      
jobs:
   SetVariables: 
    runs-on: ubuntu-latest
    outputs:
      UIBucketName: ${{ steps.Bucketid.outputs.UIBucketName }}
    steps:
     
      - id: Bucketid
        run: |
           env=${{ github.event.inputs.environment }}
           if [[ $env == agt ]]; then
             dest="dev-agt"
             echo $dest
           else 
             dest="$env"
             echo $dest
           fi
           if [ $env == wgpg ] || [ $env == aspg ]; then
               UIBucketName="cpq-$dest.agcocorp.dcx"
            else
               UIBucketName="cpq-$dest.agcocorp.com"   
            fi   
            echo $UIBucketName is bucketname
            echo "::set-output name=UIBucketName::$UIBucketName"

   second: 
    runs-on: ubuntu-latest
    needs: SetVariables
    steps:   
      - run: |
          echo ${{needs.SetVariables.outputs.dest}}
          Dest="${{needs.SetVariables.outputs.dest}}"
          echo $Dest       
          
