name: Release-test
on:
  workflow_dispatch:
   inputs:
    backdate:
      type: string
      required: true
     
      

      
jobs:
   Release: 
    runs-on: ubuntu-latest

    steps:
      - run: |
          myString="${{ inputs.backdate }}"
          newdate=$(echo ${myString:6:4}${myString:3:2}${myString:0:2})
          echo $newdate is newdate   
