name: Node

on:
  workflow_dispatch:
  
permissions:
  contents:write
  packages:write
  
jobs:
  Set_Release_Version:
    runs-on: ubuntu-latest
    outputs:
      currentversion: ${{ steps.version.outputs.currentversion }}
    steps:
       - run: |
          ReleaseVersion="1.0-SNAPSHOT"
          echo "::set-output name=currentversion::$ReleaseVersion"
  build:
    needs: Set_Release_Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@2115-27'
          
    - run:  |
       npm install --force
        pwd
        cd /home/runner/work/_temp/
        cat .npmrc 
    - run: |
        echo ${{needs.Set_Release_Version.outputs.currentversion}}
        npm run build --if-present
        ls -lrta
        cp -R foldertocopy Destdirectory 
        cp package.json Destdirectory
       
    - run:  echo refs/tags/${{needs.Set_Release_Version.outputs.currentversion}} 
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/1.0-SNAPSHOT',
            sha: context.sha
          })
    - name: publish
      run: npm install --force
    - run: |
          
          cd Destdirectory
          ls -lrta
          echo ${{needs.Set_Release_Version.outputs.currentversion}}
          git config --global user.email "athulyams2000@gmail.com"
          git config --global user.name "2115-27"
          npm version --no-git-tag-version 1.0-SNAPSHOT
          npm publish 
        
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
       
