name: Node

on:
  workflow_dispatch:

jobs:
  Checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '22.02.096'
      - run: |
         ls -lrta
     
