name: Release-test
on:
  workflow_dispatch:
  

  
jobs:
   User-API: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get user
        run: |
          gh api /user
         
        env:
           GH_TOKEN : ${{ secrets.USER }}
