name: DEPLOY
on:
  workflow_dispatch:
      inputs: 
       version:
        description: 'Version'
        default: '1.0-SNAPSHOT'
        required: true
        type: string
        

jobs:        
   Deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo testing
