name: DEPLOY
on:
  workflow_dispatch:
    inputs: 
       version:
          description: 'Version'
          default: '22.2.66'
          required: true
          type: string
       Environment1:
          type: choice
          description: env for 1.0-SNAPSHOT
          options:
          - pg
          - agt
          - wgpg
          - aspg   

jobs:        
   Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read 
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: 2115-27

      - name: Download package
        run: |
            echo ${{ github.event.inputs.version }}
            npm view @2115-27/hello-world-npm-pkg@22.2.108 dist.tarball
            npm install @2115-27/hello-world-npm-pkg@22.2.108 --legacy-peer-deps
            ls -lrta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
