name: TestDeploy

on:
  workflow_dispatch:
     inputs: 
       version:
        description: 'Version'
        default: '1.0-SNAPSHOT'
        required: true
        type: string       
       environment:
        required: true
        type: choice
        description: environment
        options: 
        - pg
        - wgpg
        - aspg
        - agt
        - dev
        - test
        - stg
        - hotfix 
jobs:
  buildnumber:
    runs-on: ubuntu-latest
    outputs:
      Component_Name: ${{ steps.CompId.outputs.Component_Name }}
    steps:
      - id: CompId  
        run: |
          echo ${{ github.run_number }} is the build number
          CompName="dcx-cpq-ui"
          echo "::set-output name=Component_Name::$CompName"
          
  DeploymentVersionUpdator:
      name: Version updator
      needs: buildnumber
      uses: ./.github/workflows/deployment-version-updator.yml
      with:
       environment: ${{ github.event.inputs.environment }}   
       CompName: dcx-cpq-ui
       ParentJobName: ${{ github.workflow }}
       
#        PARENT_JOB_ID: ${{ github.run_number }}
#        VERSION: ${{ github.event.inputs.version }}
       
