name: Release-test
on:
  workflow_dispatch:
      

      
jobs:
   Release: 
    runs-on: ubuntu-latest

    steps:
      - run: |
          myString="20/04/2023"
          Timestamp=$(`date -d "$myString" + %s`)
          FormattedDate=$(date -d "@$Timestamp" +%Y%m%d)
          echo $FormattedDate is the FormattedDate
             
