name: Release-test
on:
  workflow_dispatch:

permissions:
  contents: write
    
jobs:
   User-API: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: whoami
      - name: Get user
        run: |
          gh api /user
       
        env:
           GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
           
      - run:  git config user.name     
