name: Node

on:
  workflow_dispatch:

jobs:
  Set_Release_Version:
    runs-on: ubuntu-latest
    outputs:
      currentversion: ${{ steps.version.outputs.currentversion }}
    steps:
      - uses: actions/checkout@v2
      - id: version
        run: |
          echo setting release version!!  
          echo "${{ github.run_number }}" >> version.cfg
          newversion=$(cat version.cfg | tr -d "[:space:]")
          echo $newversion is the version
          echo "::set-output name=currentversion::$newversion"
  buildnumber:
    needs: Set_Release_Version
    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - run: echo ${{ github.run_number }} is the build number
      

