name: RUNTHIS

on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - ame: Run a one-line script
        run: echo test

