name: Node

on:
  workflow_dispatch:
      inputs: 
       version:
        description: 'Version'
        default: '1.0-SNAPSHOT'
        required: true
        type: string
       environment:
        type: choice
        description: environment
        options: 
        - pg
        - wgpg
        - aspg
        - agt
        - dev
        - test
        - stg
        - hotfix
permissions:
      contents: read
      packages: read 
      
jobs:        
   Deploy:
    runs-on: ubuntu-latest
    steps:
      - run:  |
          env=${{ github.event.inputs.environment }}
           if [[ $env == agt ]]; then
             env="dev-agt"
             echo $env
           fi
          echo $env
          configFolder="build.$env"
          UIbucketName="cpq-$env.org.com"
          echo $configFolder
          echo $UIbucketName
            
       
