name: DEPLOY
on:
  workflow_dispatch:
    inputs: 
       version:
          description: 'Version'
          default: '22.2.66'
          required: true
          type: string
       Environment:
          type: choice
          description: env for 1.0-SNAPSHOT
          options:
          - pg
          - agt
          - wgpg
          - aspg   

jobs:        
   Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read 
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
           ref: '${{ github.event.inputs.version }}'

#       - name: Node Setup
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#           registry-url: https://npm.pkg.github.com/
#           scope: 2115-27

#       - name: Download package
#         run: |
#             env = echo ${{ github.event.inputs.Environment }}
#             echo $env
#             DynaEnc=$(echo ${{ github.event.inputs.Environment }} | tr '[:lower:]' '[:upper:]')
#             echo $DynaEnc
#             npm view @2115-27/hello-world-npm-pkg@22.2.108 dist.tarball
#             wget $(npm view @2115-27/hello-world-npm-pkg@22.2.108 dist.tarball)
            
#             ls -lrta
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.GHB_TOKEN }}  
