name: Release-test
on:
  workflow_dispatch:
      

      
jobs:
   Release: 
    runs-on: ubuntu-latest

    steps:
      - run: |
          myString="20/04/2023"
          echo ${myString:6:4}${myString:0:2}${myString:3:2}
             
