name: TIME

on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          DATE_STR=$(date +%Y/%m/%d_%H:%M:%S)
          
          echo "Build Timestamp: $DATE_STR"
