name: To-lower
on:
  workflow_dispatch:
   inputs: 
       environment:
        type: choice
        description: environment
        required: true
        options: 
           - ENV1
           - ENV2
       BackDate:
        type: string
        description: BackDate
        default: ""     
        
jobs:
   
   awscli: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo aws version
          aws --version 
   lower-test: 
    runs-on: windows-latest
    steps:
      - run: |    
          $BackDate="${{ github.event.inputs.BackDate }}"
          if((![string]::IsNullOrEmpty($BackDate))) {
          write-host "BackDate: ${BackDate}"
          echo "echo printed"
          }
      - run: |
         echo "${{ github.event.inputs.environment }} is the env"
         $DynaEnv="$(echo ${{ github.event.inputs.Environment }} | tr '[:upper:]' '[:lower:]' )"
         $sourceBucket="$(echo "bar-foo-confg-model-${DynaEnv}" | tr '[:upper:]' '[:lower:]' )"
         echo "$DynaEnv is in lowercase"
         echo "$sourceBucket is the sourcebucket in lowercase"
