name: Upload

on:
  workflow_dispatch:

jobs:
  Upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir downloads
          mkdir directory
          ls -lrta
          cd directory/
          touch file1.txt file2.txt  
          ls -lrta
          
      - uses: actions/upload-artifact@v3
        with:
          name: 22.02.000
          path: ./directory 
          retention-days: 1
          
  Download-artifact:
    runs-on: ubuntu-latest
    needs: Upload-artifact
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: 22.02.000
          path: ./downloads
          
      - name: Display structure of downloaded files
        run: ls -R
          
          
