name: version

on:
  workflow_dispatch:
jobs:        
   vrsn:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.version.outputs.test }}
    steps:
     - id: stepa 
       run: |  
          variable='value'
          echo $variable
          echo "::set-output name=test::$variable"
     - name: stepb   
       run: echo ${{needs.vrsn.outputs.test}}
