name: version

on:
  workflow_dispatch:
jobs:        
   vrsn:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.stepa.outputs.test }}
    steps:
     - id: stepa 
       run: |  
          variable='value'
          echo $variable
          echo "::set-output name=test::$variable"
     - name: check   
       run: echo ${{needs.vrsn.outputs.test}}      
   second:
      runs-on: ubuntu-latest  
      needs: vrsn
      steps:
        - name: check   
          run: echo ${{needs.vrsn.outputs.test}}
