name: Workflowname

on:
  workflow_dispatch:

jobs:
  Job_One_name:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
          echo ${{ github.workflow }} is the github workflow
          echo ${{ github.job }} is the job id of the current job
      
